/**
 * Kijiji listing pack — honest MVP (Wave C).
 * No marketplace API bots. Produces clipboard text + JSON/CSV export payloads.
 * AutoTrader Canada pipe/CSV feed: see ./autotrader.ts
 */

import { parseGallery } from "@/src/lib/vehicle-image";

export type KijijiVehicleInput = {
    id: string;
    vin: string;
    year: number;
    make: string;
    model: string;
    trim?: string | null;
    odometer?: number | null;
    stock_number?: string | null;
    condition?: string | null;
    status?: string | null;
    retail_price?: number | null;
    exterior_color?: string | null;
    interior_color?: string | null;
    transmission?: string | null;
    drivetrain?: string | null;
    fuel_type?: string | null;
    body_style?: string | null;
    engine?: string | null;
    description?: string | null;
    features?: string[] | null;
    carfax_report_url?: string | null;
    image_gallery?: string[] | null;
    doors?: number | null;
    passengers?: number | null;
};

export type KijijiListingPack = {
    board: "kijiji";
    format_version: 1;
    generated_at: string;
    title: string;
    price_cad: number | null;
    category_hint: string;
    location_hint: string;
    body_text: string;
    attributes: Record<string, string | number | null>;
    image_urls: string[];
    source_vehicle_id: string;
    vin: string;
};

function money(n: number | null | undefined): string {
    if (n == null || Number.isNaN(n)) return "Call for price";
    return new Intl.NumberFormat("en-CA", {
        style: "currency",
        currency: "CAD",
        maximumFractionDigits: 0,
    }).format(n);
}

export function buildKijijiListingPack(
    vehicle: KijijiVehicleInput,
    opts?: { city?: string; province?: string }
): KijijiListingPack {
    const city = opts?.city?.trim() || "Ontario";
    const province = opts?.province?.trim() || "ON";
    const titleParts = [
        String(vehicle.year),
        vehicle.make,
        vehicle.model,
        vehicle.trim || null,
    ].filter(Boolean);
    const title = titleParts.join(" ");

    const featureLine =
        Array.isArray(vehicle.features) && vehicle.features.length > 0
            ? vehicle.features.slice(0, 12).join(", ")
            : "";

    const bodyLines = [
        title,
        "",
        `Price: ${money(vehicle.retail_price ?? null)}`,
        vehicle.odometer != null ? `Kilometers: ${vehicle.odometer.toLocaleString("en-CA")}` : null,
        vehicle.stock_number ? `Stock #: ${vehicle.stock_number}` : null,
        vehicle.condition ? `Condition: ${vehicle.condition}` : null,
        vehicle.transmission ? `Transmission: ${vehicle.transmission}` : null,
        vehicle.drivetrain ? `Drivetrain: ${vehicle.drivetrain}` : null,
        vehicle.fuel_type ? `Fuel: ${vehicle.fuel_type}` : null,
        vehicle.body_style ? `Body: ${vehicle.body_style}` : null,
        vehicle.exterior_color ? `Exterior: ${vehicle.exterior_color}` : null,
        vehicle.engine ? `Engine: ${vehicle.engine}` : null,
        vehicle.carfax_report_url ? `Vehicle history: ${vehicle.carfax_report_url}` : null,
        "",
        vehicle.description?.trim() || "Well-maintained dealership inventory. Contact us for a test drive.",
        featureLine ? `\nFeatures: ${featureLine}` : null,
        "",
        `VIN: ${vehicle.vin}`,
        `Location: ${city}, ${province}`,
        "",
        "— Listing pack generated by AdaptUs DMS (copy into Kijiji; not an auto-post).",
    ];

    const image_urls = parseGallery(vehicle.image_gallery)
        .map((img) => img.url)
        .filter((u) => /^https?:\/\//i.test(u));

    return {
        board: "kijiji",
        format_version: 1,
        generated_at: new Date().toISOString(),
        title,
        price_cad: vehicle.retail_price ?? null,
        category_hint: "Cars & Vehicles > Cars & Trucks",
        location_hint: `${city}, ${province}`,
        body_text: bodyLines.filter((l) => l !== null).join("\n"),
        attributes: {
            year: vehicle.year,
            make: vehicle.make,
            model: vehicle.model,
            trim: vehicle.trim ?? null,
            kilometres: vehicle.odometer ?? null,
            stock_number: vehicle.stock_number ?? null,
            transmission: vehicle.transmission ?? null,
            drivetrain: vehicle.drivetrain ?? null,
            fuel: vehicle.fuel_type ?? null,
            colour: vehicle.exterior_color ?? null,
            doors: vehicle.doors ?? null,
            passengers: vehicle.passengers ?? null,
            vin: vehicle.vin,
        },
        image_urls,
        source_vehicle_id: vehicle.id,
        vin: vehicle.vin,
    };
}

export function kijijiPackToCsvRow(pack: KijijiListingPack): string {
    const escape = (v: string | number | null) => {
        const s = v == null ? "" : String(v);
        if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
        return s;
    };
    const headers = [
        "title",
        "price_cad",
        "category_hint",
        "location_hint",
        "vin",
        "kilometres",
        "body_text",
        "image_urls",
    ];
    const values = [
        pack.title,
        pack.price_cad,
        pack.category_hint,
        pack.location_hint,
        pack.vin,
        pack.attributes.kilometres ?? "",
        pack.body_text,
        pack.image_urls.join(" | "),
    ];
    return `${headers.join(",")}\n${values.map(escape).join(",")}`;
}
